# Generated by Django 5.0.6 on 2024-08-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('speciality', models.CharField(max_length=64)),
                ('adress', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=64)),
            ],
        ),
    ]
