# Generated by Django 5.0.6 on 2024-08-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_doctor', '0002_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='adress',
            new_name='address',
        ),
    ]
