# Generated by Django 5.0.6 on 2024-08-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_doctor', '0003_rename_adress_doctor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_photo',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
